# Generated by Django 5.0.3 on 2024-03-26 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
